#!/usr/bin/env python3
"""Regenerate ECOSYSTEM-INDEX.md from ecosystem/atlas.json.

Run ecosystem/build_atlas.py first to rebuild atlas.json from the raw TSVs.
Usage:  python3 ecosystem/make_index.py    (from the project root)
"""
import json, collections, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(os.path.join(ROOT, "ecosystem", "atlas.json")))
P, items, cats, labels = d["packages"], d["items"], d["cats"], d["catLabels"]
PARA = {"describe": "Description", "infer": "Inference", "diffuse": "Diffusion",
        "layer": "Multilayer", "community": "Communities & phases",
        "substrate": "Static substrate"}
PARA_ORDER = ["describe", "infer", "diffuse", "layer", "community", "substrate"]

by = collections.defaultdict(list)
for i in items:
    by[i["pkg"]].append(i)

def order(n):
    if n == "Dynet":
        return (0, 0, "")
    m = P[n]
    return (1 if m["lang"] == "R" else 2, PARA_ORDER.index(m["paradigm"]), n.lower())

L = ["# Complete capability index\n",
     "Every exported function of every package surveyed in `ECOSYSTEM.md`, sorted into",
     "sixteen capability categories. Generated by `ecosystem/make_index.py` from",
     "`ecosystem/atlas.json`; raw enumerations are in `ecosystem/*.tsv`.\n",
     "Interactive version: `tmp/capability-index.html` (searchable and filterable — "
     "`open tmp/capability-index.html`).\n",
     f"**{len(items):,} functions across {len(P)} packages.** Category assignment is curated by hand",
     "for the eleven packages where the distinction carries the argument and by name-pattern rule",
     "elsewhere. *Temporal centrality* counts only time-respecting definitions — a static formula",
     "recomputed per slice is filed under *Static centrality*, Dynet's own included.\n"]

tot = collections.Counter(i["cat"] for i in items)
L += ["## Category totals\n", "| Category | Functions | Packages |", "|---|---:|---:|"]
for c in cats:
    L.append(f"| {labels[c]} | {tot[c]} | {len({i['pkg'] for i in items if i['cat'] == c})} |")
L.append("")

tc = sorted([x for x in items if x["cat"] == "centrality-t"], key=lambda x: (order(x["pkg"]), x["fn"]))
L += ["## Who implements time-respecting centrality\n",
      f"The scarcest capability in the field — {len(tc)} functions across "
      f"{len({i['pkg'] for i in tc})} packages.\n"]
L += [f"- `{i['fn']}` — **{i['pkg']}**" for i in tc]
L.append("")

nulls = collections.Counter(i["pkg"] for i in items if i["cat"] == "null")
L += ["## Who implements temporal null models\n",
      "| Package | Null / resampling functions |", "|---|---:|"]
L += [f"| {p} | {n} |" for p, n in sorted(nulls.items(), key=lambda kv: (-kv[1], kv[0]))]
L.append("\n> Dynet has **0**. This is the gap that blocks a confidence interval "
         "on every other measure.\n")

L.append("---\n\n# Package by package\n")
for name in sorted(by, key=order):
    m = P[name]
    src = " · *documentation-derived*" if m["source"] == "doc" else ""
    star = " ⭐" if name == "Dynet" else ""
    lang = "R" if m["lang"] == "R" else "Python"
    L.append(f"## {name} {m['version']}{star}")
    L.append(f"*{lang} · {PARA[m['paradigm']]}{src}* — {m['role']}\n")
    L.append(f"<sub>{len(by[name])} functions</sub>\n")
    g = collections.defaultdict(set)
    for i in by[name]:
        g[i["cat"]].add(i["fn"])
    for c in cats:
        if c not in g:
            continue
        fns = ", ".join(f"`{f}`" for f in sorted(g[c]))
        L.append(f"**{labels[c]}** ({len(g[c])}) — {fns}\n")
    L.append("")

out = os.path.join(ROOT, "ECOSYSTEM-INDEX.md")
open(out, "w", encoding="utf-8").write("\n".join(L))
print(f"wrote {out}: {len(items):,} functions, {len(P)} packages")
